
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeiuatygpnisjxlemgpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplaXVhdHlncG5pc2p4bGVtZ3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTQzNzYsImV4cCI6MjA2MzY3MDM3Nn0.MDEn6jlAr5gOQj-3zDyXih7jcsvKaZX9bVG6sse-BkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
