// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tryrbcbxqhyqnrakbpdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyeXJiY2J4cWh5cW5yYWticGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDM0MTAsImV4cCI6MjA2MDgxOTQxMH0.9lj6QB6abOsPBrVQs6exKOOxNmAGWNrmtvMh2VGnhvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);