// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hopqgbrpchpmxwjfumtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvcHFnYnJwY2hwbXh3amZ1bXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDAwMDMsImV4cCI6MjA2MDIxNjAwM30.7a8kc5u6lsN-da_i3zhGHfcPJ1y_4OOyLp72gUMFpYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);